window.playerI18n = {
    restart: 'Рестарт',
    rewind: '{seektime}с назад',
    play: 'Воспроизведение (k)',
    pause: 'Пауза',
    fastForward: '{seektime}с вперёд',
    seek: 'Seek',
    seekLabel: '{currentTime} из {duration}',
    played: 'Игран',
    buffered: 'Буферизован',
    currentTime: 'Текущее время',
    duration: 'Продолжительность',
    volume: 'Громкость',
    mute: 'Отключить звук (m)',
    unmute: 'Включить звук (m)',
    enableCaptions: 'Включить субтитров',
    disableCaptions: 'Отключить субтитров',
    enterFullscreen: 'Войти в полноэкранный режим (f)',
    exitFullscreen: 'Выйти из полноэкранного режима (Esc)',
    frameTitle: 'Плеер: {title}',
    captions: 'Субтитры',
    settings: 'Настройки (s)',
    pip: 'Картинка в картинке',
    menuBack: 'Вернуться в предыдущее меню',
    speed: 'Скорость',
    copyLink: 'Копировать метку перехода',
    normal: '1x',
    quality: 'Качество',
    changeCdn: 'Сменить сервер',
    loop: 'Повторить',
    start: 'Начало',
    end: 'Финиш',
    all: 'Все',
    reset: 'Сбросить',
    disabled: 'Выкл.',
    enabled: 'Вкл.',
    watched: 'просмотрено',
    grid_prepared: 'Видео готовится',
    grid_error: 'Процесс наложения защиты завершен c ошибкой.',
    contact_support: 'Обратитесь в поддержку.',
    qualityBadge1080: 'FullHD (1080p)',
    qualityBadge720: 'HD (720p)',
    qualityBadge576: 'SD (576p)',
    qualityBadge480: 'SD (480p)',
    createPersonalVideo: 'Получить персональное видео',
    auto: 'авто',
    auto2: 'авто ({load})',
    hotkeys: 'Cочетания клавиш',
    snapshot: 'Сделать скриншот',
    hotkeysPlayPause: 'Пауза/Проигрыш',
    hotkeysPlayPauseKeys: 'K или Пробел',
    hotkeysJumpForward: 'Перемотка вперед',
    hotkeysJumpForwardKeys: '→',
    hotkeysJumpBack: 'Перемотка назад',
    hotkeysJumpBackKeys: '←',
    hotkeysToggleFullscreen: 'Полноэкранный режим',
    hotkeysToggleFullscreenKeys: 'F',
    hotkeysMuteVolume: 'Вкл/Выкл звук',
    hotkeysMuteVolumeKeys: 'M',
    hotkeysUpVolume: 'Сделать громче',
    hotkeysUpVolumeKeys: 'Shift+↑',
    hotkeysDownVolume: 'Сделать тише',
    hotkeysDownVolumeKeys: 'Shift+↓',
    hotkeysNavigate: 'Перепрыгнуть на 10%',
    hotkeysNavigateKeys: 'цифры 0-9',
    yes: 'Да',
    no: 'Нет',
    youStopped: 'Вы остановились на {savedCurrentTime}',
    wouldLikeContinue: 'Продолжить',
    wouldLikeStart: 'Сначала',
    errorLoadVideo: 'Ошибка! Что-то пошло не так',
    errorVideoNotAvailable: 'Видео недоступно',
    goodQualityWarning: 'Обработка видео в хорошем качестве поставлена в очередь и появится позже',
    goodQualityWarning2: 'Это сообщение видит только администратор',
    cdnSlowMsg: "Подождите, загружаем видео ... {percent}%",
    cdnChangeMsg: "Подождите, выбираем сервер ... {percent}%",
    cdnErrorsMsg: "Неполадки сети, ищем доступный сервер",
    cdnErrorsMsgNative: "Неполадки сети, идет загрузка видео...",
    linkIsCopy: "Метка скопирована в буфер обмена",
    errorLinkCopy: "Произошла ошибка при копировании метки",
    middleInternetSpeedMsg: 'Наблюдаются перебои в работе интернета',
    badInternetSpeedMsg: 'Скорость интернета недостаточна для просмотра видео',
    needChangeCdnQ1: 'Заметили, что видео медленно загружается или прерывается.',
    needChangeCdnQ2: 'Смените сервер, чтобы восстановить соединение',
    serverNum: 'Сервер #{n}',
    yesSelf: 'Да, выбрать самостоятельно',
    yesAuto: 'Да, выбрать сервер автоматически',
    noAndNo: 'Нет, и больше не спрашивать',
    noContinue: 'Нет, продолжить просмотр',
    serverNotFound: 'Сервер не найден',
    windowTopError: 'Блокировка. Открытие вне сайта',
    downloadAttemptError: 'Блокировка. Попытка скачивания видео(Internet Download Manager)',
    yesOpenBookmark: 'Открыть закладку',
    removeBookmark: 'Удалить закладку',
    needOpenBookmark: 'Вы хотите открыть закладку?',
    bookmarkIsCreate: 'Закладка сохранена',
    bookmarkErrorCreate: 'Произошла ошибка при сохранении закладки',
    bookmarkIsEdit: 'Время закладки изменено',
    bookmarkErrorEdit: 'Произошла ошибка при редактировании закладки',
    bookmarkIsRemove: 'Закладка удалена',
    bookmarkErrorRemove: 'Произошла ошибка при удалении закладки',
    bookmark: 'Закладка',
    initError: 'Произошла ошибка при инициализации плеера',
    vpnDetectQ1: 'У вас происходит задержка в видео из-за включённого VPN',
    vpnDetectQ2: 'Выключите его и перезапустите страницу',
    okCloseVpn: 'ОК, закрыть',
    okHideVpn: 'ОК, не показывать это сообщение',
    idVideoLabel: 'ID Видео',
    settingsH1: 'Настройки',
    second: 'секунд',
    video: 'видео'
}
